export * from "./audiences/audiences.controller";
export * from "./businesses/businesses.controller";
export * from "./emails/emails.controller";
export * from "./recipients/recipients.controller";
export * from "./senders/senders.controller";
export * from "./templates/template.controller";
export * from "./user/user.controller";
export * from "./segments/segments.controller";
export * from "./version/version.controller";
